### ISSUE TITLE
How to implement reset button behaviour?

### ISSUE THREAD

**Issue by barseghyanartur** [paramquery/select#2]
Hello,

I have a reset button (button[type=reset]) and want to clear all selections on click. Is that possible? How?

Thanks in advance.

**Comment by paramquery** [comment]
It can be done by clearing the value of select list and use of refreshData API of paramquery select.

http://paramquery.com/api/select#method-refreshData

http://jsfiddle.net/4jo4tod5/

**Comment by barseghyanartur** [comment]
@paramquery 

Thanks!
