### ISSUE TITLE
Setting the maxDisplay property to 0

### ISSUE THREAD

**Issue by barseghyanartur** [paramquery/select#4]
Setting the maxDisplay property to 0 doesn't work.

It gets back to the default value (4). I had to set the default value to 0 in order to get the desired behaviour, but it would be nice if 0 would be just accepted as an option, instead of considering it as not specified.

**Comment by paramquery** [comment]
Ok, i guess that would require setting default value to -1

**Comment by barseghyanartur** [comment]
@paramquery 

Worked! Thanks.
