### ISSUE TITLE
needs a way to custom style everything.

### ISSUE THREAD

**Issue by jspreddy** [paramquery/select#6]
Make the plugin custom styleable. As it stands now, I can't change the styling without changing it inline in the plugin js file.

Extract all the styling strings (css classes) into the options object.
Default options will have default styling strings.
Can pass in custom styling classes.

**Comment by paramquery** [comment]
It's not needed to make changes in js file to customize styling. All the styling is done by assigning classes which are in css file. you can have a look at the css file and override the styles by writing your own css rules for those classes.

Some of the classes can be modified or added with help of options like hoverCls and selectCls

Probably addition of options to inject classes in various states and to different regions of the select list would be more appropriate.

**Comment by jspreddy** [comment]
Agreed. I can write styling to override all the styling classes used in there and get a decent looking thingy.
My requirement is that I want to restyle this using `bootstrap` and not use any `jQuery-UI` classes.
Is there any other way to do that?

**Comment by paramquery** [comment]
Ok, I see what you mean. I guess you want to assign bootstrap classes to different regions/parts of the select list?

That's a nice suggestion, support for it would be added probably in the next version.

**Comment by paramquery** [comment]
Just an addition: There is a jsfiddle of customizing css with existing classes in pqSelect

http://jsfiddle.net/dLvx6u63/11/

and the common classes are documented here:

https://github.com/paramquery/select/wiki/Css-customization

**Comment by massic80** [comment]
Current release lacks an important class: see #5 from @barseghyanartur.
This would be a quick amend!
